name: causality
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.8.12
  - pip:
    - dowhy==0.6
    - folium==0.12.1.post1
    - matplotlib==3.5.0
    - numpy==1.20.3
    - pandas==1.3.4
    - scikit-learn==1.0.1
    - seaborn==0.11.2
